package com.gameaholix.coinops.game;

import android.os.Parcel;
import android.os.Parcelable;

public class Game implements Parcelable {

//    public enum Type {
//        PINBALL("Pinball", 0),
//        VIDEOGAME("Videogame", 1);
//
//        private String stringValue;
//        private int intValue;
//
//        Type(String toString, int value) {
//            stringValue = toString;
//            intValue = value;
//        }
//
//        @Override
//        public String toString() {
//            return stringValue;
//        }
//    }


//    public enum Type { pinball, videogame }
//    public enum Cabinet { original, conversion, board_only }
//    public enum Condition { AP, A, AM, BP, B, BM, CP, C, CM, D, F, Unknown }
//    public enum Working { yes, no, partial, unknown }
//    public enum MonitorSize { s13in, s19in, s23in, s25in, s27in }
//    public enum MonitorType { bw_raster, color_raster, bw_vector, color_vector }
//    public enum Status { own, sold, want }

    private String gameId;
    private String name;
    private String manufacturer;
    private int year;

    private String type;
    private String cabinet;
    private String condition;
    private String working;

    private String monitorSize;
    private String monitorType;
    private String monitorChassis;
    private String tubeModel;

    private String serialNumber;
    private String highScore;
    private String comment;
    private String status;

    private Boolean forSale;
    private Double boughtPrice;
    private Double forSalePrice;

    public Game() {
        // Default constructor required for calls to DataSnapshot.getValue()
    }

    public Game(String name) {
        this.name = name;
    }

    private Game(Parcel in) {
        this.gameId = in.readString();
        this.name = in.readString();
        this.manufacturer = in.readString();
        this.year = in.readInt();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int i) {
        dest.writeString(gameId);
        dest.writeString(name);
        dest.writeString(manufacturer);
        dest.writeInt(year);
    }

    public final static Parcelable.Creator<Game> CREATOR = new Parcelable.Creator<Game>() {

        @Override
        public Game createFromParcel(Parcel in) { return new Game(in); }

        @Override
        public Game[] newArray(int size) { return (new Game[size]); }
    };

    // checks if two Game objects are equal by comparing gameId which should be unique
    // as gameId is generated by firebase
    public boolean equals(Object object) {
        if (object instanceof Game) {
            Game game = (Game) object;
            return getGameId() == game.getGameId();
        } else {
            return false;
        }
    }

    public String getGameId() { return gameId; }

    public void setGameId(String gameId) { this.gameId = gameId; }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }
}
