package com.gameaholix.coinops.game;

import android.os.Parcel;
import android.os.Parcelable;

public class Game implements Parcelable {

    private String gameId;
    private String name;
    private String manufacturer;
    private String year;

    public Game() {
        // Default constructor required for calls to DataSnapshot.getValue()
    }

    public Game(String name) {
        this.name = name;
    }

    private Game(Parcel in) {
        this.gameId = in.readString();
        this.name = in.readString();
        this.manufacturer = in.readString();
        this.year = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int i) {
        dest.writeString(gameId);
        dest.writeString(name);
        dest.writeString(manufacturer);
        dest.writeString(year);
    }

    public final static Parcelable.Creator<Game> CREATOR = new Parcelable.Creator<Game>() {

        @Override
        public Game createFromParcel(Parcel in) { return new Game(in); }

        @Override
        public Game[] newArray(int size) { return (new Game[size]); }
    };

    // checks if two Game objects are equal by comparing gameId which should be unique
    // as gameId is generated by firebase
    public boolean equals(Object object) {
        if (object instanceof Game) {
            Game game = (Game) object;
            return getGameId() == game.getGameId();
        } else {
            return false;
        }
    }

    public String getGameId() { return gameId; }

    public void setGameId(String gameId) { this.gameId = gameId; }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }
}
