package com.gameaholix.coinops.game;

public class Game {

    private String gameId;
    private String name;
    private String manufacturer;
    private String year;

    public Game() {
        // Default constructor required for calls to DataSnapshot.getValue(Game.class)
    }

    public Game(String name) {
        this.name = name;
    }

    // checks if two Game objects are equal by comparing gameId which should be unique
    // as gameId is generated by firebase
    public boolean equals(Object object) {
        if (object instanceof Game) {
            Game game = (Game) object;
            return getGameId() == game.getGameId();
        } else {
            return false;
        }
    }

    public String getGameId() { return gameId; }

    public void setGameId(String gameId) { this.gameId = gameId; }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }
}
