package com.gameaholix.coinops.shopping;

import android.os.Parcel;
import android.os.Parcelable;

public class ShoppingItem implements Parcelable {

    private String id;
    private String name;

    public ShoppingItem() {
        // Default constructor required for calls to DataSnapshot.getValue()
    }

    public ShoppingItem(String name) {
        this.name = name;
    }

    private ShoppingItem(Parcel in) {
        this.id = in.readString();
        this.name = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int i) {
        dest.writeString(id);
        dest.writeString(name);
    }

    public final static Parcelable.Creator<ShoppingItem> CREATOR = new Parcelable.Creator<ShoppingItem>() {

        @Override
        public ShoppingItem createFromParcel(Parcel in) { return new ShoppingItem(in); }

        @Override
        public ShoppingItem[] newArray(int size) { return (new ShoppingItem[size]); }
    };

    // checks if two ShoppingItem objects are equal by comparing gameId which should be unique
    // as id is generated by firebase
    public boolean equals(Object object) {
        if (object instanceof ShoppingItem) {
            ShoppingItem shoppingItem = (ShoppingItem) object;
            return getId() == shoppingItem.getId();
        } else {
            return false;
        }
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
