package com.gameaholix.coinops.todo;

import android.os.Parcel;
import android.os.Parcelable;

public class ToDoItem implements Parcelable{

    private String id;
    private String name;

    public ToDoItem() {
        // Default constructor required for calls to DataSnapshot.getValue()
    }

    public ToDoItem(String name) {
        this.name = name;
    }

    private ToDoItem(Parcel in) {
        this.id = in.readString();
        this.name = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int i) {
        dest.writeString(id);
        dest.writeString(name);
    }

    public final static Parcelable.Creator<ToDoItem> CREATOR = new Parcelable.Creator<ToDoItem>() {

        @Override
        public ToDoItem createFromParcel(Parcel in) { return new ToDoItem(in); }

        @Override
        public ToDoItem[] newArray(int size) { return (new ToDoItem[size]); }
    };

    // checks if two ToDoItem objects are equal by comparing gameId which should be unique
    // as id is generated by firebase
    public boolean equals(Object object) {
        if (object instanceof ToDoItem) {
            ToDoItem toDoItem = (ToDoItem) object;
            return getId() == toDoItem.getId();
        } else {
            return false;
        }
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
