package com.gameaholix.coinops.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.firebase.database.Exclude;
import com.google.firebase.database.ServerValue;

import java.util.Map;

public class Entry implements Parcelable{
    private String id;
    private String parentId;
    private String entry;
    private long createdAt;
    private long modifiedAt;

    public Entry() {
        // Default constructor required for calls to DataSnapshot.getValue()
    }

    public Entry(String id, String parentId, String entry) {
        this.id = id;
        this.parentId = parentId;
        this.entry = entry;
    }

    private Entry(Parcel in) {
        this.id = in.readString();
        this.parentId = in.readString();
        this.entry = in.readString();
        this.createdAt = in.readLong();
        this.modifiedAt = in.readLong();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int i) {
        dest.writeString(id);
        dest.writeString(parentId);
        dest.writeString(entry);
        dest.writeLong(createdAt);
    }

    public final static Parcelable.Creator<Entry> CREATOR = new Parcelable.Creator<Entry>() {

        @Override
        public Entry createFromParcel(Parcel in) { return new Entry(in); }

        @Override
        public Entry[] newArray(int size) { return (new Entry[size]); }
    };

    // checks if two Entry objects are equal by comparing parentId which should be unique
    // as id is generated by firebase
    public boolean equals(Entry log) {
        return getId().equals(log.getId());
    }

    @Exclude
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getEntry() {
        return entry;
    }

    public void setEntry(String entry) {
        this.entry = entry;
    }

    public Map<String, String> getCreatedAt() {
        return ServerValue.TIMESTAMP;
    }

    @Exclude
    public Long getCreatedAtLong() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public long getModifiedAt() {
        return modifiedAt;
    }

    public void setModifiedAt(long modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
}
