package com.gameaholix.coinops.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.firebase.database.Exclude;

public class InventoryItem implements Parcelable {

    private String id;
    private String name;
    private int type;
    private int condition;
    private String description;

    public InventoryItem() {
        // Default constructor required for calls to DataSnapshot.getValue()
    }

    public InventoryItem(String name) {
        this.name = name;
    }

    private InventoryItem(Parcel in) {
        this.id = in.readString();
        this.name = in.readString();
        this.type = in.readInt();
        this.condition = in.readInt();
        this.description = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int i) {
        dest.writeString(id);
        dest.writeString(name);
        dest.writeInt(type);
        dest.writeInt(condition);
        dest.writeString(description);
    }

    public final static Parcelable.Creator<InventoryItem> CREATOR = new Parcelable.Creator<InventoryItem>() {

        @Override
        public InventoryItem createFromParcel(Parcel in) { return new InventoryItem(in); }

        @Override
        public InventoryItem[] newArray(int size) { return (new InventoryItem[size]); }
    };

    // checks if two InventoryItem objects are equal by comparing gameId which should be unique
    // as id is generated by firebase
    public boolean equals(InventoryItem inventoryItem) {
        return getId().equals(inventoryItem.getId());
    }

    // Exclude id from being written to database as a field (id is already the parent node)
    @Exclude
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public int getCondition() {
        return condition;
    }

    public void setCondition(int condition) {
        this.condition = condition;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
