package com.gameaholix.coinops.model;

import android.os.Parcel;
import android.os.Parcelable;

import com.google.firebase.database.Exclude;
import com.google.firebase.database.ServerValue;

import java.util.Map;

public class Item implements Parcelable{
    private String id;
    private String gameId;
    private String name;
    private long createdAt;
    private long modifiedAt;

    public Item() {
        // Default constructor required for calls to DataSnapshot.getValue()
    }

    public Item(String id, String gameId, String name) {
        this.id = id;
        this.gameId = gameId;
        this.name = name;
    }

    private Item(Parcel in) {
        this.id = in.readString();
        this.gameId = in.readString();
        this.name = in.readString();
        this.createdAt = in.readLong();
        this.modifiedAt = in.readLong();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int i) {
        dest.writeString(id);
        dest.writeString(gameId);
        dest.writeString(name);
        dest.writeLong(createdAt);
    }

    public final static Creator<Item> CREATOR = new Creator<Item>() {

        @Override
        public Item createFromParcel(Parcel in) { return new Item(in); }

        @Override
        public Item[] newArray(int size) { return (new Item[size]); }
    };

    // checks if two Entry objects are equal by comparing gameId which should be unique
    // as id is generated by firebase
    public boolean equals(Item log) {
        return getId().equals(log.getId());
    }

    @Exclude
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getGameId() {
        return gameId;
    }

    public void setGameId(String gameId) {
        this.gameId = gameId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Map<String, String> getCreatedAt() {
        return ServerValue.TIMESTAMP;
    }

    @Exclude
    public Long getCreatedAtLong() {
        return createdAt;
    }

    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    public long getModifiedAt() {
        return modifiedAt;
    }

    public void setModifiedAt(long modifiedAt) {
        this.modifiedAt = modifiedAt;
    }
}
