package com.gameaholix.coinops.inventory;

import android.os.Parcel;
import android.os.Parcelable;

public class InventoryItem implements Parcelable {

    private String id;
    private String name;

    public InventoryItem() {
        // Default constructor required for calls to DataSnapshot.getValue()
    }

    public InventoryItem(String name) {
        this.name = name;
    }

    private InventoryItem(Parcel in) {
        this.id = in.readString();
        this.name = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int i) {
        dest.writeString(id);
        dest.writeString(name);
    }

    public final static Parcelable.Creator<InventoryItem> CREATOR = new Parcelable.Creator<InventoryItem>() {

        @Override
        public InventoryItem createFromParcel(Parcel in) { return new InventoryItem(in); }

        @Override
        public InventoryItem[] newArray(int size) { return (new InventoryItem[size]); }
    };

    // checks if two InventoryItem objects are equal by comparing gameId which should be unique
    // as id is generated by firebase
    public boolean equals(Object object) {
        if (object instanceof InventoryItem) {
            InventoryItem inventoryItem = (InventoryItem) object;
            return getId() == inventoryItem.getId();
        } else {
            return false;
        }
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
